# These are supported funding model platforms

# github: santoshvandari
# open_collective: santosh-bhandari
ko_fi: santoshvandari
buy_me_a_coffee: santoshvandari
custom: ["https://buymemomo.com/santoshvandari",docx_viewer]
